<template>
  <div class="loadingio-spinner-dual-ball-qi8lenc8h7l">
    <div class="ldio-asdm06d6c6w">
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<script>
export default {};
</script>

<style>
@keyframes ldio-asdm06d6c6w-o {
  0% {
    opacity: 1;
    transform: translate(0 0);
  }
  49.99% {
    opacity: 1;
    transform: translate(44.66px, 0);
  }
  50% {
    opacity: 0;
    transform: translate(44.66px, 0);
  }
  100% {
    opacity: 0;
    transform: translate(0, 0);
  }
}
@keyframes ldio-asdm06d6c6w {
  0% {
    transform: translate(0, 0);
  }
  50% {
    transform: translate(44.66px, 0);
  }
  100% {
    transform: translate(0, 0);
  }
}
.ldio-asdm06d6c6w div {
  position: absolute;
  width: 44.66px;
  height: 44.66px;
  border-radius: 50%;
  top: 79.16999999999999px;
  left: 56.839999999999996px;
}
.ldio-asdm06d6c6w div:nth-child(1) {
  background: #d3d033;
  animation: ldio-asdm06d6c6w 0.8064516129032259s linear infinite;
  animation-delay: -0.40322580645161293s;
}
.ldio-asdm06d6c6w div:nth-child(2) {
  background: #c05790;
  animation: ldio-asdm06d6c6w 0.8064516129032259s linear infinite;
  animation-delay: 0s;
}
.ldio-asdm06d6c6w div:nth-child(3) {
  background: #d3d033;
  animation: ldio-asdm06d6c6w-o 0.8064516129032259s linear infinite;
  animation-delay: -0.40322580645161293s;
}
.loadingio-spinner-dual-ball-qi8lenc8h7l {
  width: 203px;
  height: 203px;
  display: inline-block;
  overflow: hidden;
}
.ldio-asdm06d6c6w {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-asdm06d6c6w div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
